[tool.ruff]
line-length = 120
indent-width = 4
lint.extend-select = ["I"]
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "messages.py",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.codespell]
write-changes = false
skip = '*./logs,*./venv,*./vscode,*./github,*./__pycache__,*./ruff_cache'
