name: Deployment

on:
  workflow_dispatch:

jobs:
  lint-workflow-call:
      uses: MorpheusBot/Morpheus/.github/workflows/main.yml@master

  Deployment_Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: lint-workflow-call
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Execute deployment on SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          port: 22
          script: |
            cd Morpheus
            git pull
            docker compose down && docker compose up --build -d
